#pragma once

enum class GFMMState {ERROR=-1, NOT_READY=0, READY_TO_START=2, HEADING_TOWARD_ENTRANCE=3, SEARCHING_FOR_FIRE=4, FIRE_DETECTED = 5, 
                                        APPROACHING_FIRE=6, POSITIONING_UGV=7, EXTINGUISHING_FIRE=8, RETURNING_TO_BASE=9, FINISHED=10};